roles/console/files/help/Config.rst, roles/console/files/help/Control.rst, roles/console/files/help/InstContent.rst, roles/console/files/help/Overview.rst, roles/console/files/help/Utilities.rst, roles/console/files/htmlf/10-control.html, roles/console/files/htmlf/20-configure.html, roles/console/files/htmlf/40-install_content.html, roles/console/files/htmlf/70-utilities.html, roles/console/files/index.html, roles/console/templates/xs-console-ssl.conf.j2
awstats config is still outstanding
=> remove school from labels and elsewhere

roles/cmdsrv/tasks/packages.yml
=> change mod-wsgi to mod_wsgi

roles/console/files/js/admin_console.js, roles/console/templates/cmd-service.wsgi.j2
=> substitute %20 for space so jquery ajax doesn't convert to plus sign

roles/console/files/htmlf/20-configure.html
=> sugar-stats to sugar_stats

roles/console/files/help/Config.rst, roles/console/files/help/Overview.rst, roles/console/files/htmlf/20-configure.html, roles/console/files/htmlf/40-install_content.html, roles/console/files/htmlf/70-utilities.html
I just accidentally pushed my edits to [roles/console/files/help](https://github.com/iiab/iiab-admin-console/tree/master/roles/console/files/help) without a PR, changing these 4 files:
- [Config.rst](https://github.com/iiab/iiab-admin-console/blob/master/roles/console/files/help/Config.rst) ([commit](https://github.com/iiab/iiab-admin-console/commit/71ffc9543715472367fb9fbba0e16fd1aba9b0be#diff-2f19f191524edd0c485bd52ec439af33))
- [InstContent.rst](https://github.com/iiab/iiab-admin-console/blob/master/roles/console/files/help/InstContent.rst) ([commit](https://github.com/iiab/iiab-admin-console/commit/397fc97db4bc349461ce87c212bcf69fdbee0601#diff-f8e60127122e16055acdcdbe77cac01a))
- [Overview.rst](https://github.com/iiab/iiab-admin-console/blob/master/roles/console/files/help/Overview.rst …
=> Admin Console Docs Cleanup: typos, Lan -> LAN, Zim -> ZIM, etc

roles/cmdsrv/files/iiab-cmdsrv, roles/cmdsrv/templates/scripts/get_oer2go_catalog
smoke and function tests passed
=> merge our catalog into oer2go

roles/cmdsrv/tasks/main.yml
=> python-systemd->systemd-python

roles/console/files/js/admin_console.js
=> more accommodate rename of variable in iiab

roles/console/templates/server-info.php
=> cancelling error, but variable name wrong

iiab-admin.yml, roles/cmdsrv/files/iiab-cmdsrv, roles/cmdsrv/templates/cmdsrv.conf.j2
tested on rpi
this may be too severe and in need of tuning of the nice string
=> Add priority to long running jobs

roles/cmdsrv/files/iiab-cmdsrv, roles/console/files/htmlf/70-utilities.html, roles/console/files/js/admin_console.js
=> change job stat to show duration

roles/cmdsrv/templates/scripts/iiab_update_menus.py
=> remove testing code

roles/cmdsrv/templates/scripts/iiab_update_menus.py
missing search item in description
=> 0.3 gh fix2

roles/cmdsrv/templates/scripts/iiab_update_menus.py
=> 0.3 gh fix3

roles/js-menu/files/menu-files/js/js-menu.js
=> accomodate missing zim_versions_idx in js-menus.js

roles/cmdsrv/files/scripts/oer2go_install_move.sh, roles/cmdsrv/files/scripts/zim_install_move.sh, roles/cmdsrv/files/scripts/zim_install_step3.sh, roles/cmdsrv/templates/scripts/get_oer2go_catalog, roles/cmdsrv/templates/scripts/iiab_update_menus.py
get these in, some changes are already in 0.3-devel
=> 0.3 gh fix8

iiab-admin.yml, roles/cmdsrv/templates/scripts/iiab_update_menus.py, roles/console/files/help/ContentMenus.rst, roles/console/files/htmlf/40-install_content.html, roles/console/files/htmlf/50-edit_menus.html, roles/console/files/js/js_menu_functions.js, roles/js-menu/files/menu.json
=> expose autoupdate_menu field and use it in updates

roles/console/files/js/js_menu_functions.js
=> fix auto load of home page and missing function

roles/console/files/osm/iiab-install-map, roles/console/tasks/main.yml, roles/js-menu/files/menu-files/js/js-menu.js, vars/default_vars.yml
Requires companion changes to iiab
=> Regional Tile selection Osmap2

roles/console/files/css/iiab.css
Thanks @floydianslips
Refs: iiab/iiab#877 iiab/iiab#1605 iiab/iiab#1612 iiab/iiab#1619 iiab/maps#2 iiab/maps#3
=> Josh's css to raise "Install Selected Region" button in map "continent" picker

roles/console/files/js/osm_functions.js
As iiab/iiab#1621 was insufficient, given @georgehunt explained today[*] that code deprecated.
[*] during our IIAB call @ http://minutes.iiab.io
=> Cleaner Admin Console "Continent Picker" to download & install OSM vector maps

roles/console/files/htmlf/50-edit_menus.html, roles/js-menu/files/menu-files/js/js-menu.js, roles/js-menu/files/menu-files/menu-defs/en-external.json
add external links to js-menu and admin console
=> External Links

roles/cmdsrv/files/iiab-cmdsrv, roles/console/files/js/js_menu_functions.js, roles/js-menu/utilities/menu-def-converter
=> 0.3.6.1 devel

roles/console/files/htmlf/50-edit_menus.html, roles/console/files/js/admin_console.js, roles/console/files/js/js_menu_functions.js, roles/console/templates/upload-image.php
WIP. no error checking, but basic upload works.
=> upload menu item icon initial check in

roles/console/files/js/js_menu_functions.js
=> escape newline and quote for json fields

roles/console/files/css/iiab.css
Fixes scroll from exiting modal.
=> fixed scrolling issue

roles/js-menu/files/menu-files/menu-defs/fr-haitifutur.json
Fixed error in start url.
> I have just now tested and there is one error in the fr-haitifutur file. Not sure how you want to change that but it has been fixed in my fork.
@KW4NP just to be 100% sure your new PR here (https://github.com/iiab/iiab-admin-console/commit/20b2283b4347b16744ab06daf3878c839b3f5347) is correct...even though it looks like it's going onto the internet for "www.haitifutur.com" ...that's actually just a directory named www.haitifutur.com right ?
=> Update fr-haitifutur.json, building on #196

roles/console/files/htmlf/50-edit_menus.html, roles/console/files/js/js_menu_functions.js, roles/js-menu/files/menu-files/js/js-menu.js, roles/js-menu/files/menu-files/services/set-server-time.php, roles/js-menu/files/menu.json, roles/js-menu/tasks/main.yml, roles/js-menu/templates/021_apache_set_time.j2, roles/js-menu/templates/config.json.j2
if mobile device or win64 or macintel
and if apache sudo and turned on in menu
=> set system time from browser time

.gitignore, roles/cmdsrv/files/iiab-cmdsrv, roles/console/files/css/iiab.css, roles/console/files/index.html, roles/console/files/js/admin_console.js
This is a preview. 
Vpn and bluetooth are mostly working.
=> Add vpn, bluetooth, and hotspot control to Admin Console

roles/js-menu/files/menu-files/menu-defs/en-coreknowledge.json
=> en-coreknowledge_CoreKnowledge_logo.png -> en-coreknowledge.png

roles/console/files/js/admin_console.js, roles/console/files/js/map_functions.js
The one line was going to be map_functions.js L126 (change region to url). But nothing is ever as simple in the end as it seems at first.
Tested in debian8 VM. Refuses to download what is already installed. Refuses to download a url that is in mapWip. Will download a new version of a map, that has a new URL.
=> Oneline fix

roles/cmdsrv/templates/cmdsrv.conf.j2
(at least until there is another proxy)
=> use iiab variable proxy for squid service

roles/cmdsrv/files/iiab-cmdsrv, roles/console/files/js/admin_console.js, roles/js-menu/files/index.html, roles/js-menu/files/menu-files/css/js-menu.css, roles/js-menu/files/menu-files/js/js-menu.js
generate error if internet required for command and not present
eliminate config vars
toggle display in home page
=> August 2019 Enhancements

cp-menus, iiab-admin.yml, install, roles/cmdsrv/tasks/main.yml, roles/cmdsrv/templates/scripts/install_menu_defs.py, roles/cmdsrv/templates/scripts/sync_menu_defs.py, roles/cmdsrv/templates/utilities/iiab-sync-menu-defs, roles/common/tasks/main.yml, roles/common/templates/adm_lib.py.j2, roles/js-menu/files/menu-files/deprecated-menu-item-defs/ar-wikipedia_ar_medicine_apk.json, roles/js-menu/files/menu-files/deprecated-menu-item-defs/ar-wikipedia_ar_medicine_noapk.json, roles/js-menu/files/menu-files/deprecated-menu-item-defs/en-wikipedia_en_medicine_apk.json, roles/js-menu/files/menu-files/deprecated-menu-item-defs/es-wikipedia_es_medicine_apk.json, roles/js-menu/files/menu-files/deprecated-menu-item-defs/fr-wikipedia_fr_medicine_apk.json, roles/js-menu/files/menu-files/js/js-menu.js, roles/js-menu/tasks/install_menu_defs.yml, roles/js-menu/tasks/main.yml, vars/default_vars.yml
This is phase I where only a manual interface is available namely running
`iiab-sync-menu-defs`
Phase II will add a button to Admin Console to run this.
Phase III will sync each time a menu def is edited.
=> Sync Menu Item Definitions between local files and central repo (0.3.8)

roles/js-menu/tasks/main.yml
add back copying of js, etc that was in cp-menus
=> 0.3.9 fixes

roles/js-menu/files/menu-files/js/js-menu.js
Permits android <8 to display the menu items in the dumb browser.
=> test for local storage

roles/js-menu/files/menu-files/js/js-menu.js
add some vscode formatting as well
=> race condition processing page before loading it

roles/cmdsrv/templates/scripts/iiab-update-map3.py, roles/common/templates/adm_const.py.j2, roles/common/templates/adm_lib.py, roles/console/files/js/admin_console.js, roles/js-menu/files/menu-files/js/js-menu.js, vars/default_vars.yml
=> 0.4.0.8 tweaks

roles/common/templates/adm_lib.py, roles/console/files/js/js_menu_functions.js, roles/js-menu/files/menu-files/js/js-menu.js
This is phase I only manual edit. Later we may add a channel dropdown.
=> 0.4.1.0 misc - add Kolibri channel id to menus

roles/cmdsrv/files/iiab-cmdsrv3.py, roles/cmdsrv/files/scripts/wr-sdcard-params.sh, roles/console/files/js/admin_console.js
sdcard dirs vary over platforms
eth0 was hardcoded for rpi but doesn't exist on W
preparation for ap0
=> 0.4.1.0 fixes

roles/cmdsrv/tasks/main.yml
passed smoke and functional tests on vm
=> remove creation of link that is no longer used

roles/cmdsrv/files/iiab-cmdsrv3.py
this was tested an works. not sure whether it is truly necessary.
=> switch test for internet access to neverssl.com

roles/js-menu/tasks/main.yml
=> move regions.json to /etc/iiab

roles/cmdsrv/files/iiab-cmdsrv3.py
=> logic backwards

roles/console/files/js/admin_console.js
thought this was already done.
=> filter uninstalled and unchanged variables

roles/console/files/index.html, roles/console/tasks/main.yml
=> subjective changes to form

roles/console/templates/admin-console-nginx.conf.j2
This addresses iiab #2448 -- moodle .../admin/ not working.
=> console stealing all admin

iiab-admin.yml, install, roles/cmdsrv/tasks/main.yml, roles/js-menu/tasks/main.yml
add -n switch so developers can run install without the downloads
=> move final role function and catalog downloads to install script

install
replacement of final role with cmdsrv restart in install neglected to enable it
=> tag on fix that cmdsrv not enabled

roles/console/files/js/admin_console.js, roles/console/files/js/js_menu_functions.js
=> add cloned menu item def to menu

roles/cmdsrv/files/presets/fr-school/content.json, roles/cmdsrv/files/presets/fr-school/menu.json
add maxi to zim name and create fr-kalite_en menu def. text in FR but lang code EN to trigger port 8008
=> wrong names in fr preset

roles/console/files/htmlf/40-install_content.html
As discussed with @tim-moody on this week's IIAB community call @ http://minutes.iiab.io
Towards helping people resolve things like...
- https://github.com/iiab/iiab/issues/3067#issuecomment-995993472
Tangentially related:
- iiab/iiab#3062
- iiab/iiab#3065
- iiab/iiab#3068
cc: @icebox827 @avni
=> Install Content > Quick Pick: Refine instructions

roles/console/tasks/main.yml
https://github.com/iiab/iiab/pull/3015
=> softcode - defined in iiab/vars/default_vars.yml

roles/console/files/htmlf/40-install_content.html
Proposed changes to intro/explanation text and minor layout changes
=> Proposed changes to [Quick Pick] intro/explanation text

roles/cmdsrv/templates/scripts/get_oer2go_catalog3.py, roles/common/templates/adm_lib.py
check for non-existent menu def was done after exit for non-existent new item
=> correct faulty logic in update home menu

roles/console/files/htmlf/70-utilities.html
=> Fix CHGPW instructions typo in console/files/htmlf/70-utilities.html

vars/Linux Mint.yml
=> solve df problem in linux mint

docs/5.Content.md
=> docs/5.Content.md: Two tiny typos fixed, sorry I missed these earlier

roles/console/files/help/Control.rst, roles/console/files/htmlf/20-configure.html
Refining...
- PR #539 
- PR #549
Related:
- #546 
- PR #548
=> Admin Console help typos & suggestions

roles/cmdsrv/files/iiab-cmdsrv3.py
only root can see it, but to be safe
=> don't log authentication

roles/cmdsrv/files/iiab-cmdsrv3.py, roles/common/templates/adm_const.py.j2, roles/common/templates/adm_lib.py, roles/console/files/css/iiab.css, roles/console/files/index.html, roles/console/files/js/admin_console.js
tested on rpi w2 with intermittent problem iiab/iiab#3750
=> Show list of upstream routers for  connection

roles/js-menu/files/menu-files/js/js-menu.js
Try to report server connection idling timeout.
I am unable to reproduce this so I can't test it.
Only test I have is this does not break if there is a connection.
=> check jqXHR status for != 200

roles/common/templates/adm_const.py.j2, roles/console/files/htmlf/20-configure.html
allow installation of tailscale from Admin Console
tested on ub 24.04.1 vm
=> add tailscale to admin console

roles/js-menu/files/menu-files/js/js-menu.js
- It was assumed that loading menu.json either succeeded or failed
- However, since it is asynchronously bundled with other file loads, if one of those fails it never completes
- So capture state of all three initial file loads to more accurately report any failure
=> capture more status as menus load

ansible.cfg
details at https://github.com/iiab/iiab/pull/3948 https://github.com/iiab/iiab/pull/3947#issuecomment-2661566053
=> Update ansible.cfg use full path to virtual environment

roles/cmdsrv/templates/scripts/upgrade-zims.py
=> avoid running upgrade on all simply with no args
